local petsList = {
	Common = {
		"Cat",
		"Dog",
		"Hamster",
		"Bunny",
		"Chick",
		"Duck",
		"Pig",
		"Fish",
	},

	Rare = {
		"Goldfish",
		"Gecko",
		"Sealion",
		"Chicken",
		"Sheep",
		"Cheetah",
		"Panda",
		"Persian",
		"Cow",
		"Wolf",
		"Brown Rabbit",
		"Mouse",
		"Frog",
		"Bear",
		"Bird",
	},

	Epic = {
		"Fox",
		"Lizard",
		"Husky",
		"Goat",
		"Elephant",
		"Parrot",
		"Raccoon",
		"Deer",
		"Calico",
		"Snake",
		"Turtle",
		"Squirrel",
		"Monkey",
		"Lion",
	},

	Mythic = {
		"Tiger",
		"Capybara",
		"Owl",
		"Poodle",
	},

	Legendary = {
		"Hedgehog",
		"Sugar Glider",
		"Cobra",
		"Eagle",
	},

	Godly = {
	},

	Mysterious = {
	}
}

return petsList
